const mockNotes = {
	"1a2b": {
		title: "Morning Thoughts",
		img: "https://picsum.photos/300/200",
		content: "Started the day with coffee and some journaling.",
		color: "bubblegumCrisis",
		date: "Apr 1, 2026",
	},
	"2b3c": {
		title: "Workout Log",
		img: "https://picsum.photos/300/200",
		content: "Leg day today. Squats and lunges done.",
		color: "emptiness",
		date: "Apr 2, 2026",
	},
	"3c4d": {
		title: "Recipe Idea",
		img: "https://picsum.photos/300/200",
		content: "Try banana pancakes with honey drizzle.",
		color: "bananaBread",
		date: "Apr 3, 2026",
	},
	"4d5e": {
		title: "Project Notes",
		img: "https://picsum.photos/300/200",
		content: "Need to refactor the routing logic.",
		color: "pineapplePerfume",
		date: "Apr 4, 2026",
	},
	"5e6f": {
		title: "Travel Plan",
		img: "https://picsum.photos/300/200",
		content: "Plan a weekend trip to the hills.",
		color: "peachFizz",
		date: "Apr 5, 2026",
	},
	"6f7g": {
		title: "Book List",
		img: "https://picsum.photos/300/200",
		content: "Read Atomic Habits and Deep Work.",
		color: "#1E1E2F",
		date: "Apr 6, 2026",
	},
	"7g8h": {
		title: "Ideas",
		img: "https://picsum.photos/300/200",
		content: "Build a mini notes app with hash routing.",
		color: "#FFB6C1",
		date: "Apr 7, 2026",
	},
	"8h9i": {
		title: "Meeting Notes",
		img: "https://picsum.photos/300/200",
		content: "Discussed UI improvements and UX flow.",
		color: "#FFDAB9",
		date: "Apr 8, 2026",
	},
	"9i0j": {
		title: "Shopping List",
		img: "https://picsum.photos/300/200",
		content: "Milk, eggs, bread, fruits.",
		color: "#FFFACD",
		date: "Apr 9, 2026",
	},
	"0j1k": {
		title: "Random Thought",
		img: "https://picsum.photos/300/200",
		content: "Consistency beats motivation.",
		color: "#FFE4B5",
		date: "Apr 10, 2026",
	},
	"1k2l": {
		title: "UI Ideas",
		img: "https://picsum.photos/300/200",
		content: "Add smooth transitions between views.",
		color: "#FFB6C1",
		date: "Apr 11, 2026",
	},
	"2l3m": {
		title: "Coding Notes",
		img: "https://picsum.photos/300/200",
		content: "Learn more about closures in JS.",
		color: "#1E1E2F",
		date: "Apr 12, 2026",
	},
	"3m4n": {
		title: "Goals",
		img: "https://picsum.photos/300/200",
		content: "Finish project by end of month.",
		color: "#FFDAB9",
		date: "Apr 13, 2026",
	},
	"4n5o": {
		title: "Music List",
		img: "https://picsum.photos/300/200",
		content: "Create a chill playlist.",
		color: "#FFE4B5",
		date: "Apr 14, 2026",
	},
	"5o6p": {
		title: "Daily Log",
		img: "https://picsum.photos/300/200",
		content: "Had a productive coding session.",
		color: "#FFFACD",
		date: "Apr 15, 2026",
	},
	"6p7q": {
		title: "App Features",
		img: "https://picsum.photos/300/200",
		content: "Add edit and delete functionality.",
		color: "#FFB6C1",
		date: "Apr 16, 2026",
	},
	"7q8r": {
		title: "Notes",
		img: "https://picsum.photos/300/200",
		content: "Remember to backup localStorage.",
		color: "#1E1E2F",
		date: "Apr 17, 2026",
	},
	"8r9s": {
		title: "Brainstorm",
		img: "https://picsum.photos/300/200",
		content: "Think about adding tags to notes.",
		color: "#FFDAB9",
		date: "Apr 18, 2026",
	},
	"9s0t": {
		title: "Design",
		img: "https://picsum.photos/300/200",
		content: "Use soft pastel color palette.",
		color: "#FFE4B5",
		date: "Apr 19, 2026",
	},
	"0t1u": {
		title: "Wrap Up",
		img: "https://picsum.photos/300/200",
		content: "Clean code and finalize UI.",
		color: "#FFFACD",
		date: "Apr 20, 2026",
	},
};

localStorage.setItem("notes", JSON.stringify(mockNotes));
